import os
import requests
import json

def detect_ai_content(text):
    """
    Analyzes text to determine the probability it was generated by an LLM.
    Returns a JSON object with a score (0-100) and reasoning.
    """
    nim_api_key = os.getenv("NIM_API_KEY")
    url = "https://integrate.api.nvidia.com/v1/chat/completions"
    
    headers = {
        "Authorization": f"Bearer {nim_api_key}",
        "Content-Type": "application/json"
    }

    system_prompt = """
    You are an expert linguistic forensic analyst specializing in AI text detection.
    Analyze the user's text for common LLM artifacts:
    1. Lack of burstiness (varying sentence lengths).
    2. Low perplexity (highly predictable word choices).
    3. Common LLM phrasing (e.g., "It is important to note", "In conclusion", "Delve").
    
    Calculate a probability score from 0 to 100 where 100 means definitely AI-generated, and 0 means definitely human-written.
    
    Output STRICTLY in JSON format:
    {
      "ai_probability_score": <int>,
      "analysis": "<A 1-sentence explanation of why you gave this score>"
    }
    """

    payload = {
        "model": "meta/llama-3.3-70b-instruct",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Analyze this text:\n\n{text}"}
        ],
        "temperature": 0.1,
        "max_tokens": 256,
        "response_format": {"type": "json_object"}
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        result = response.json()
        
        content = result['choices'][0]['message']['content']
        return json.loads(content)

    except Exception as e:
        print(f"Detection Error: {e}")
        return {"ai_probability_score": 0, "analysis": "Error analyzing text."}